# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjZITv8rp_fba5m3bsWHXhq8yNBkpqOH
"""

import streamlit as st
import pickle
import numpy as np
import pandas as pd

# Load model
model = pickle.load(open("hospital_model.sav", "rb"))

st.title("🏥 Hospital Treatment Cost Prediction")

st.write("This app predicts treatment costs and suggests a package price.")

# Example input fields (replace with your dataset’s real features!)
age = st.number_input("Patient Age", min_value=0, max_value=120, value=40)
stay_days = st.number_input("Expected Length of Stay (days)", min_value=1, max_value=60, value=5)
disease = st.selectbox("Disease Type", ["Heart Surgery", "Angioplasty", "Bypass Surgery", "Other"])
room_type = st.selectbox("Room Type", ["General", "Private", "ICU"])

# Convert categorical inputs to numbers (simple example)
disease_map = {"Heart Surgery": 0, "Angioplasty": 1, "Bypass Surgery": 2, "Other": 3}
room_map = {"General": 0, "Private": 1, "ICU": 2}

# Prepare input for model
input_data = np.array([[age, stay_days, disease_map[disease], room_map[room_type]]])

if st.button("Predict Cost"):
    prediction = model.predict(input_data)[0]
    package_price = prediction * 1.1  # add 10% buffer
    st.success(f"Predicted Treatment Cost: ₹{prediction:,.0f}")
    st.info(f"Suggested Package Price: ₹{package_price:,.0f}")



!pip install streamlit